name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Build
          run: ./build.ps1
          shell: pwsh